spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:~/h2;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456